# 项目相关配置
wqm:
  # 名称
  name: 汪启铭
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/user/uploadPath，Linux配置 /home/uploadPath）
  #  profile: D:/Learn/uploadPath
  profile: /tmp/tools/uploadPath

# spring配置
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: dyl
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        ## connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        connectionProperties:
          druid:
            stat:
              mergeSql: true
              slowSqlMillis: 5000
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.100.192.14:3306/tools?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: tools
          password: DYL010924.